### ISSUE TITLE
Don't require yarn

### ISSUE THREAD

**Issue by TheJaredWilcurt** [AndrewR3K/browser-extension-boilerplate#1]
Was looking for a browser extension boilerplate and Google brought me here. I immediately assumed the repo had been unmaintained for 5-8 years when I saw "Yarn" in the README. Yarn only got popular because it was faster than npm 3 and had some additional features. But since npm 5 (2017), Yarn has been slower, and npm has had equivalent features since npm 8 (2021). There are some very specific niche differences for monorepos that some may find value in, but other than that, Yarn is generally not as good of an option compared to just regular npm now.

**Comment by AndrewR3K** [comment]
Thanks for the heads up!! Ill definitely remove yarn in the next update
